includes:
  - base.yaml
model:
  model_name: vGIN
  generative_model_name: SODAugNN
  dim_ffn: 600
ood:
  ood_alg: SODAug
  ood_param: 0.5  # pairL_per
  ood_alg_gen: SODAug_pre
  extra_param:
    - 0.1     # kl
    - 0.2     # br_num
    - 0.2     # attr
    - 20     # max_k
    - 0.6     # pl_loss
    - 10     # Vrex
    - 1e-3     # main lr
    - 60     # pre epoch
    - 1      # no frag
    - 0      # scaffold/basis
    - 0.8    # percentage of data aug
train:
  max_epoch: 200
  lr: 1e-4
dataset:
  dataloader_name: PairDataLoader


