includes:
  - base.yaml
model:
  model_name: vGIN
  generative_model_name: SODAugNN
  dim_ffn: 600
ood:
  ood_alg: SODAug
  ood_param: 0.5  # pairL_per
  ood_alg_gen: SODAug_pre
  extra_param:
    - 1.2     # kl
    - 0.1     # br_num
    - 0.2     # attr
    - 20     # max_k
    - 0.8     # pl_loss
    - 0     # Vrex
train:
  max_epoch: 200
  lr: 1e-4
dataset:
  dataloader_name: PairDataLoader


