includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 0  # infomation constraint
  extra_param:
    - 1    # LA
    - 0      # EC
    - 1     # EA
    - 10     # r decay interval
    - 0.001       # EF
train:
  max_epoch: 200
  lr: 1e-3
  pre_train: 150


