includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 1.0  # infomation constraint
  extra_param:
    - 0.1    # LA
    - 0      # EC
    - 0.01     # EA
    - 60     # r decay interval
    - 0.1       # EF
    - true  # If batchnorm/instancenorm (true/false)
train:
  max_epoch: 200
  lr: 1e-3
  pre_train: 155


