includes:
  - base.yaml
model:
  model_name: GINSimclr
ood:
  ood_alg: Momu
  ood_param: 0
  extra_param:
    - 1.0    # vrex
train:
  max_epoch: 100
  lr: 1e-3
  tr_ctn: True
pre_ckpt_path: '/data/xinerli/MoMu/Pretrain/all_checkpoints/pretrain_gin/sci-bert-epoch=299-step=18300.ckpt'


