includes:
  - base.yaml
model:
  model_name: GINSimclr
ood:
  ood_alg: Momu
  ood_param: 0.1
train:
  max_epoch: 200
  lr: 1e-3
  tr_ctn: True
pre_ckpt_path: '/data/xinerli/MoMu/Pretrain/all_checkpoints/pretrain_gin/epoch=299-step=18300.ckpt'


