exp_round:
  - 11
  - 12
weight_decay:
  - 0.
  - 1e-3
  - 1e-4
  - 1e-5
lr:
  - 1e-3
extra_param:
  -     # learn_edge_att
    - true
  -      # decay_interval
    - 10
    - 20
  -      # final_r
    - 0.5
    - 0.7