includes:
  - base.yaml
model:
  model_name: GEIGIN
ood:
  ood_alg: GEI
  ood_param: 0  # infomation constraint
  extra_param:
    - 1    # LA
    - 0.01      # EC
    - 0.01     # EA
    - 10     # r decay interval
    - 1     # EF
    - true  # batchnorm or instancenorm for EF
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]
  pre_train: 100


