includes:
  - base.yaml
model:
  model_name: Sub_GIN
ood:
  ood_alg: Subnetwork
  ood_param: 1e-4
train:
  max_epoch: 200
  lr: 1e-3
  stage_stones: [150]
  weight_decay: 0
  mile_stones: [150]
#  train_bs: 128