includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 1.0  # infomation constraint
  extra_param:
    - 0.01    # LA
    - 0.01      # EC
    - 0.01     # EA
    - 10     # r decay interval
train:
  max_epoch: 200
  lr: 1e-3
  pre_train: 100


