exp_round:
#  - 1
#  - 2
  - 3
log_file:
  - exp_0
lr:
  - 1e-3
  - 1e-4
#  - 1e-2
weight_decay:
  - 0.
#  - 1e-3
#  - 1e-4
pre_ckpt_path:
  - '/data/xinerli/MoMu/Pretrain/all_checkpoints/pretrain_gin/sci-bert-epoch=299-step=18300.ckpt'
  - '/data/xinerli/MoMu/Pretrain/all_checkpoints/pretrain_gin/epoch=299-step=36600.ckpt'
