includes:
  - ../base.yaml
  - ../../GOODHIV.yaml
ood_param:
  - 1
extra_param:
  -     # LA
    - 1
    - 0.75
    - 0.5
    - 0.25
    - 0.1
    - 0.075
    - 0.05
  -      # EC
    - 0
  -      # EA
    - 0.01
  -       # r decay interval
    - 60
  -       # EF
    - 0
  -
    - true
#    - false
pre_train:
  - 50