includes:
  - ../base.yaml
  - ../../GOODTwitter.yaml
ood_param:
  - 1
extra_param:
  -     # LA
    - 0.7
    - 0.5
    - 0.3
    - 0.1
    - 7.5e-2
    - 5e-2
    - 2.5e-2
  -      # EC
    - 0
  -      # EA
    - 0.001
#    - 0
  -       # r decay interval
    - 30
  -       # EF
    - 0.001
  -
    - true
pre_train:
  - 5