includes:
  - ../base.yaml
  - ../../GOODSST2.yaml
lr:
  - 1e-3
#  - 1e-4
weight_decay:
  - 0.
#  - 1e-3
#  - 1e-4
#  - 1e-5
ood_param:
  - 0
  - 1
extra_param:
  -     # LA
#    - 10
    - 1
    - 0.1
  -      # EC
    - 0
  -      # EA
#    - 10
    - 1
    - 0.1
  -       # r decay interval
    - 30
#    - 40
  -       # EF
    - 0
    - 0.01
    - 0.001
    - 0.0001
  -
#    - true
    - false
pre_train:
  - 50