includes:
  - base.yaml
model:
  model_name: DANN_GIN
ood:
  ood_alg: DANN
  ood_param: 0.01
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
log_file: exp_0
clean_save: true
