includes:
  - ../base.yaml
  - ../../GOODMotif.yaml
ood_param:   # information constraint
  - 0
#  - 1
extra_param:
  -     # LA
    - 20
    - 10
    - 5
    - 1
#    - 0.1
#    - 0.01
  -      # EC
    - 0
#    - 0.001
  -      # EA
#    - 100
    - 20
    - 10
    - 5
    - 1
#    - 0.1
#    - 0.01
  -       # r decay interval
    - 50
  -       # EF
    - 0
#    - 0.1
#    - 0.01
#    - 0.001
  -           # If batchnorm/instancenorm (true/false)
    - true
#    - false
pre_train:
  - 100