task: train
random_seed: 123
exp_round: null
log_file: default
gpu_idx: 0
ckpt_root: null
ckpt_dir: null
pre_ckpt_path: null
save_tag: null
other_saved: null
pytest: False
train:
  weight_decay: 0.
  save_gap: 10
  tr_ctn: False
  epoch: 0
  ctn_epoch: 0
  alpha: 0.2  # parameter for DANN
  stage_stones: []
  mile_stones: [200]
model:
  dim_hidden: 300
  dim_ffn: 300
  dropout_rate: 0.5
  generative_model_name: null
dataset:
  dataloader_name: BaseDataLoader
  dataset_root: null
  generate: False
  dim_node: null
  dim_edge: null
  num_classes: null
  num_envs: null
ood:
  extra_param: null
  ood_alg_gen: null