exp_round:
  - 1
  - 2
lr:
  - 1e-3
ood_param:   # information constraint
  - 0
  - 1
extra_param:
  -     # LA
    - 0
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
    - 0.1
    - 0.01
  -      # EA
    - 0
    - 0.1
    - 0.01
  -       # r decay interval
    - 10