exp_round:
  - 1
  - 2
lr:
  - 1e-3
ood_param:   # information constraint
  - 0
#  - 1
extra_param:
  -     # LA
    - 100
    - 10
    - 1
  -      # EC
    - 0
    - 0.001
  -      # EA
    - 10
    - 1
    - 0.1
  -       # r decay interval
    - 10