exp_round:
#  - 1     # GEI_v0.1.0
#  - 2
#  - 3        # GEI_v0.2.0
#  - 4
#  - 5         # GEI_v0.2.1 careful lr
#  - 6
  - 7           # GEI_v0.2.2 later EA
  - 8
lr:
  - 1e-3
ood_param:   # sub gnn learning rate
  - 1e-3
  - 1e-2
  - 1e-1
#  - 1
extra_param:
  -     # LA lr / EA lr: * self.LA * self.EA
    - 1
    - 10
    - 100
  -      # EC
    - 0
#    - 0.001
  -      # EA lr / EA gnn lr: * self.EA
    - 1
    - 1e-1
    - 1e-2
  -       # r decay interval
    - 10