includes:
  - base.yaml
model:
  model_name: Coral_vGIN
ood:
  ood_alg: Coral
  ood_param: 0.001
train:
  max_epoch: 200
  lr: 0.001
  weight_decay: 0.0
  pre_train: 50
log_file: exp_0
clean_save: true
