includes:
  - ../base.yaml
  - ../../DD.yaml
ood_param:   # information constraint
#  - 0
  - 1
extra_param:
  -     # LA
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 0.01
    - 0.001
  -       # r decay interval
    - 60
  -       # EF
    - 0
    - 0.1
    - 0.01
  -           # If sub extractor batchnorm/instancenorm (true/false)
    - true
#    - false
pre_train:
  - 50