includes:
  - ../base.yaml
  - ../../GOODTwitter.yaml
ood_param:
#  - 0
  - 1
extra_param:
  -     # LA
#    - 10
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
  -      # EA
#    - 10
    - 1
    - 0.1
    - 0.01
    - 0.001
  -       # r decay interval
    - 60
    - 30
  -       # EF
    - 0
    - 0.1
    - 0.01
    - 0.001
#    - 0.0001
  -
    - true
#    - false
pre_train:
  - 5