includes:
  - base.yaml
model:
  model_name: DANN_vGIN
ood:
  ood_alg: DANN
  ood_param: 1.0
train:
  max_epoch: 500
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
