includes:
  - base.yaml
model:
  model_name: Sub_vGIN
ood:
  ood_alg: Subnetwork
  ood_param: 1e-4
train:
  max_epoch: 1100
#  tr_ctn: True
#  ctn_epoch: 140
  lr: 1e-3
  stage_stones: [500, 600]
  mile_stones: [300]