includes:
  - ../base.yaml
  - ../../GOODMotif.yaml
ood_param:   # information constraint
  - 0
extra_param:
  -     # LA
    - 7
    - 5
    - 3
    - 1
    - 0.75
    - 0.5
    - 0.25
#    - 0
  -      # EC
    - 0
  -      # EA
    - 20
  -       # r decay interval
    - 50
  -       # EF
    - 0
  -           # If batchnorm/instancenorm (true/false)
    - true
pre_train:
  - 100