includes:
  - ../base.yaml
  - ../../GOODSST2.yaml
extra_param:
  -
    - 0.05     # kl
  -
    - 0.08     # br_num
  -
    - 0.2     # attr
  -
    - 13     # max_k
  -
    - 0.8     # pl_loss
  -
    - 0     # Vrex
    - 50
    - 10
    - 100
  -
    - 1e-3     # main lr
  -
    - 60     # pre epoch
  -
    - 0      # no frag
    - 1
  -
    - 0      # scaffold/basis reorg
    - 1
  -
    - 0.8    # percentage of data aug
    - 1.
    - 0.6