includes:
  - ../base.yaml
  - ../../LBAPcore.yaml
ood_param:   # information constraint
#  - 0
  - 1
extra_param:
  -     # LA
#    - 10
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
  -      # EA
#    - 10
#    - 1
    - 0.1
    - 0.01
    - 0.001
  -       # r decay interval
#    - 60
    - 90
  -       # EF
#    - 0
    - 0.1
    - 0.01
#    - 0.001
  -           # If batchnorm/instancenorm (true/false)
    - true
#    - false
pre_train:
  - 20