includes:
  - base.yaml
model:
  model_name: vGIN
ood:
  ood_alg: feat_aug
  ood_param: 1e-1
train:
  max_epoch: 500
  train_bs: 64
  lr: 1e-3
  mile_stones: [300]
dataset:
  dataloader_name: PairDataLoader
