includes:
  - base.yaml
model:
  model_name: vGIN
ood:
  ood_alg: IRM
  ood_param: 0.1
train:
  max_epoch: 500
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
