includes:
  - base.yaml
model:
  model_name: PL_vGIN
ood:
  ood_alg: PairL
  ood_param: 0.5
  extra_param:
    - 30
train:
  max_epoch: 500
  train_bs: 64
  lr: 1e-3
  mile_stones: [300]
dataset:
  dataloader_name: PairDataLoader
