includes:
  - ../base.yaml
  - ../../GOODHIV.yaml
ood_param:
  - 1
extra_param:
  -     # LA
    - 1
  -      # EC
    - 0
  -      # EA
    - 0.07
    - 0.05
    - 0.03
    - 0.01
    - 7.5e-3
    - 5e-3
    - 2.5e-3
  -       # r decay interval
    - 60
  -       # EF
    - 0
  -
    - true
#    - false
pre_train:
  - 50