includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 0  # infomation constraint
  extra_param:
    - 100    # LA
    - 0      # EC
    - 10     # EA
    - 10     # r decay interval
    - 0       # EF
train:
  max_epoch: 200
  lr: 1e-3
  pre_train: 50
  mile_stones: [300]
  train_bs: 64
  val_bs: 128
  test_bs: 128

