includes:
  - base.yaml
model:
  model_name: ASAPvGIN
ood:
  ood_alg: ASAP
  ood_param: 0.8
train:
  max_epoch: 200
  train_bs: 32
  lr: 0.0001
  weight_decay: 0.0001
log_file: exp_0
clean_save: true
