includes:
  - base.yaml
model:
  model_name: ASAPvGIN
ood:
  ood_alg: ASAP
  ood_param: 0.6
train:
  max_epoch: 500
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
