includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.6     # causal ratio
  extra_param:
    - 1e-4
train:
  train_bs:
  max_epoch: 500
  lr: 1e-3
  mile_stones: [300]

