includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 1e-2  # sub gnn learning rate
  extra_param:
    - 10    # LA
    - 0      # EC
    - 1     # EA
    - 10     # r decay interval
train:
  max_epoch: 200
  lr: 1e-3
  pre_train: 50
  mile_stones: [150]
  train_bs: 64
  val_bs: 128
  test_bs: 128


