includes:
  - base.yaml
model:
  model_name: GIN
  global_pool: max
  generative_model_name: VGAE
  dim_ffn: 600
ood:
  ood_alg: G_splice
  ood_param: 0.1
  ood_alg_gen: G_splice_generative
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]


